# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.233.112:3306/take_out
    username: root
    password: 123456
  redis:
    host: 192.168.233.112
    port: 6379
    password: 123456
  rabbitmq:
    host: 192.168.233.112
    port: 5672 # 端口
    virtual-host: / # 虚拟主机
    username: r # 用户名
    password: 123456 # 密码
    listener:
      simple:
        prefetch: 1 # 每次只能获取一条消息，处理完成才能获取下一个消息
    publisher-confirm-type: correlated
mybatis-plus:
  mapper-locations: "classpath*:/mapper/**/*.xml"
  global-config:
    db-config:
      id-type: auto



server:
  port: 7777
